name: deTech
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.6.6
    - jupyter=1.0.0
    - nbconvert=5.4.0
    - pandas=0.23.4
    - xlrd=1.1.0
    - pip:
        - plotly==3.4.0
        - datasheets==0.1.3
